server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/uniquelogindb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
  output:
    ansi:
      enabled: always
logging:
  level:
    com.xiaoyu.demo.xiaoyu.unique.login.mapper: trace